### ISSUE TITLE
fails to compile on debian 9.1 

### ISSUE THREAD

**Issue by jacobzlogar** [obsidianproject/Obsidian-Qt#37]
Tested on latest commit (774667f511284230a4c86702993e17931271fa46)

As well as (536821bf3b87e63442242b83cbb792e17edc11e4)

Error:
```In file included from chainparams.h:9:0,
                 from alert.cpp:7:
bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from allocators.h:12,
                 from serialize.h:22,
                 from alert.h:9,
                 from alert.cpp:5:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from chainparams.h:9:0,
                 from alert.cpp:7:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:62:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
```

Possibly OpenSSL ?

https://github.com/FeatherCoin/Feathercoin/issues/177

https://github.com/bitcoin/bitcoin/issues/7086

https://github.com/bitcoin/bitcoin/pull/7095

**Comment by jacobzlogar** [comment]
Debian 8.9 - 9.1 confirmed affected

**Comment by netsfx** [comment]
works on my machine (Ubuntu 16.04)

**Comment by netsfx** [comment]
I think Debian might need a build-debian.sh, I mean an own build script. Building on a Debian has never been tested with our wallet.

**Comment by netsfx** [comment]
Try this? - Create file build-debian.sh with:

export PKG_CONFIG_PATH="/usr/lib/openssl-1.0/pkgconfig" //CHANGE TO OWN OPENSSL PATH
export CXXFLAGS+=" -I/usr/include/openssl-1.0" //CHANGE TO OWN OPENSSL PATH
export LDFLAGS+=" -L/usr/lib/openssl-1.0 -lssl" //CHANGE TO OWN OPENSSL PATH

src/buildquick.sh


and run:
./build-debian.sh

**Comment by jacobzlogar** [comment]
Okay @netsfx

**Comment by petermcclory** [comment]
Did this fix the issue?

**Comment by jacobzlogar** [comment]
Negative

**Comment by netsfx** [comment]
try build-new.sh
